# Generated by Django 5.1.5 on 2025-05-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_userprofile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PrecioProducto',
        ),
        migrations.DeleteModel(
            name='UnidadVenta',
        ),
    ]
