# Generated by Django 5.1.5 on 2025-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0009_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_tienda',
            field=models.IntegerField(default=0),
        ),
    ]
