# Generated by Django 5.1.5 on 2025-06-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token_ws',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
