# Generated by Django 5.1.5 on 2025-06-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_token_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_retiro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
