# Generated by Django 5.1.5 on 2025-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_metodo_retiro_pedido_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PAG', 'Pagado'), ('PRE', 'En preparación'), ('RET', 'Pendiente de retiro'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEND', max_length=4),
        ),
    ]
